services:
  - type: web
    name: supermarket-shopping-list
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://postgres.umzormxrpriczendcfls:11309211wW.%21@aws-0-us-west-2.pooler.supabase.com:6543/postgres?pgbouncer=true
      - key: DIRECT_URL
        value: postgresql://postgres.umzormxrpriczendcfls:11309211wW.%21@aws-0-us-west-2.pooler.supabase.com:5432/postgres
